### ISSUE TITLE
RHEL only?

### ISSUE THREAD

**Issue by aldycool** [digitalis-io/k3s-on-prem-production#4]
Hi,

I haven't read all of the Ansible tasks, but I'm currently using Ubuntu distros for the nodes, and fixing here and there for the difference in packages (such as replacing `crond` with `cron`, `audit` with `auditd`, and so on). I'm beginning to wonder, or maybe it is mentioned somewhere in the README, is it tested / meant for CentOS only? I gave up at the error: "Update Grub and Initramfs /RedHat". Thanks.

**Comment by 89luca89** [comment]
Hi @aldycool 

I think it is written in the blog post that is based on this project that it has been tested on CentOS but it should work on Debian family distros too

Anyway, using `host_vars` you can override the package names, just override 

```yaml
aide_package: 'aide'
auditd_package: 'audit'
modprobe_package: 'kmod'
```

with whatever is the package name variation 

---

For the update grub part, the code supports both 

```yaml
- name: Update Grub and Initramfs /RedHat
  command: '{{ item }}'
  with_items:
    - 'grub2-mkconfig -o /boot/grub2/grub.cfg'
    - 'dracut --force --regenerate-all -v'
  when:
    - grub_setup_1.changed or grub_setup_2.changed or package_update.changed
    - ansible_os_family == "RedHat"

- name: Update Grub and Initramfs /Debian
  command: '{{ item }}'
  with_items:
    - 'update-grub'
  when:
    - grub_setup_1.changed or grub_setup_2.changed or package_update.changed
    - ansible_os_family == "Debian"
```

So either it's not picking up the ansible_os_family correctly or I'm not really sure what else is happening.

Let me know if overriding the host_vars fixes your problem :smile:
